FROM resin/%%RESIN_MACHINE_NAME%%-python

ENV INITSYSTEM on

RUN echo i2c-bcm2708 >> /etc/modules
RUN echo i2c-dev >> /etc/modules

RUN apt-get update && \
apt-get install -y build-essential python-dev python-smbus python-pip i2c-tools

RUN pip install -U setuptools speedtest-cli && \
pip install Adafruit-CharLCD && \
LC_ALL=C pip install RPi.Gpio &&  \
rm -rf /var/lib/apt/lists/*

COPY . /app

CMD ["python", "/app/SpeedTestCheck.py"]
